### ISSUE TITLE
"This executable was compiled without using Go modules"

### ISSUE THREAD

**Issue by rfay** [mitchellh/golicense#1]
I just gave it a run with [ddev](https://github.com/drud/ddev) and get 
```
$ golicense ddev
⚠️  "ddev" ⚠️

This executable was compiled without using Go modules or has
zero dependencies. golicense considers this an error (exit code 1).
```

Well, it uses dep, not go modules... but it has lots in the vendor directory. Most projects haven't converted to modules yet.  To test, you can just download ddev from releases.

**Comment by mitchellh** [comment]
golicense requires Go modules to work, since it extracts dependency information from the compiled metadata in the binary from Go modules. This project doesn't scan vendor directories. There are other source-based license scanners if you want to do that, but the goal of this project is binary-based since its much more accurate (assuming an untampered binary).

**Comment by mitchellh** [comment]
I just realized that at some point when modifying the README this requirement was also lost... I'll update that!

**Comment by mitchellh** [comment]
Heh sorry, that's my bias, we're switching everything over to Go modules and I've used Go modules exclusively since 1.11 and most of the other companies I'm close with are switching as well. I expect most projects will fully adopt Go modules over the next couple years!
